name = "BayesTime"
uuid = "d9a7c0d8-790a-43c4-973b-029d0c48e73c"
version = "0.1.0"
authors = ["tscheckel <tobias.scheckel@hotmail.de>"]

[deps]
CovarianceMatrices = "60f91f6f-d783-54cb-84f9-544141854719"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCDiagnosticTools = "be115224-59cd-429b-ad48-344e309966f0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
CovarianceMatrices = "0.30.3"
DataFrames = "1.8.1"
Distributions = "0.25.122"
LinearAlgebra = "1.12.0"
MCMCDiagnosticTools = "0.3.15"
Plots = "1.41.3"
